package Classes_UI;

import Classes_Base.*;

/** @author Mateus */
public class GrcProdutos_P extends javax.swing.JPanel {

  /** Creates new form MenuGestãoProdutos */
  UIGovernor_F janela;

  public GrcProdutos_P(UIGovernor_F janela) {
    this.janela = janela;

    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    this.framePrincipal = janela.getFrame();
    jComboBox1 = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    botaoAdd = new javax.swing.JButton();
    botaoEdit = new javax.swing.JButton();
    botaoIn = new javax.swing.JButton();
    botaoOut = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    tableData1 =
        new javax.swing.table.DefaultTableModel(
            new String[] {"Código", "Nome", "Quantidade", "Preço"}, 0);

    int size = Estoque.sizeOfEstoque();
    if (size > 0) {
      for (int i = 0; i < size; i++) {
        Produto p = Estoque.buscarProduto(i);
        if (p != null) {
          Object[] data = p.toData();
          data[0] = new Integer(i);
          tableData1.addRow(data);
        }
      }
    }

    jComboBox1.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    jTable1.setModel(tableData1);

    jScrollPane1.setViewportView(jTable1);

    botaoAdd.setText("Cadastrar Produto");
    botaoAdd.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            botaoAddClicked(evt);
          }
        });

    botaoEdit.setText("Editar Produto");
    botaoEdit.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            botaoEditClicked(evt);
          }
        });

    botaoIn.setText("Entrada no Estoque");
    botaoIn.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            botaoInClicked(evt);
          }
        });

    botaoOut.setText("Saída no Estoque");
    botaoOut.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            botaoOutClicked(evt);
          }
        });

    jButton6.setText("Menu");
    jButton6.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton6MouseClicked(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(
                                        jButton6,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        86,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        botaoAdd,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(
                                                        botaoEdit,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(37, 37, 37)
                                                    .addComponent(
                                                        botaoIn,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(
                                                        botaoOut,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(37, 37, 37))
                                            .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                733,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(33, Short.MAX_VALUE)))));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                botaoAdd,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                70,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                botaoEdit,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                70,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                botaoIn,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                70,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                botaoOut,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                70,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        353,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton6,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                43,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE)));
  } // </editor-fold>//GEN-END:initComponents

  private void botaoAddClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jButton6MouseClicked
  }

  private void botaoEditClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jButton6MouseClicked
    janela.removeMenuGerencProdutos();
    janela.menuOPC();
  }

  private void botaoInClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jButton6MouseClicked
    janela.removeMenuGerencProdutos();
    janela.menuOPC();
  }

  private void botaoOutClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jButton6MouseClicked
    janela.removeMenuGerencProdutos();
    janela.menuOPC();
  }

  private void jButton6MouseClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jButton6MouseClicked
    janela.removeMenuGerencProdutos();
    janela.menuOPC();
  } // GEN-LAST:event_jButton6MouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFrame framePrincipal;
  private javax.swing.JButton botaoAdd;
  private javax.swing.JButton botaoEdit;
  private javax.swing.JButton botaoIn;
  private javax.swing.JButton botaoOut;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.table.DefaultTableModel tableData1;
  // End of variables declaration//GEN-END:variables
}
