package Classes_UI;

import Classes_Base.Usuário;
import Classes_Base.Usuários;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Mateus
 */
public class Login_P extends javax.swing.JPanel {
    UIGovernor_F UImaster;
    
    protected void populaSeletorUsuário(UIGovernor_F UImaster){
        this.Login_SeletorUsuário_JComboBox.removeAllItems();
        
        UImaster.UserBase.getUserList().forEach( (usuário) -> {
            this.Login_SeletorUsuário_JComboBox.addItem(usuário);  //popula a caixa de seleção de usuários
            
        });
        
        if(UImaster.UserBase.getUserList().isEmpty()){
            primeiroCadastro_botão.setEnabled(true);  //trava o botão "primeiro cadastro" se já existirem usuarios cadastrados
            Login_OK_botão.setEnabled(false);
        }
            
        else{
            primeiroCadastro_botão.setEnabled(false);
            Login_OK_botão.setEnabled(true);
        }
            
    }
    
    public Login_P(UIGovernor_F UImaster) {
        this.UImaster = UImaster;
        initComponents();
        populaSeletorUsuário(UImaster);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autenticar_jLabel = new javax.swing.JLabel();
        Login_SeletorUsuário_JComboBox = new javax.swing.JComboBox<>();
        Login_SelecUsuario_label = new javax.swing.JLabel();
        senha_jLabel = new javax.swing.JLabel();
        Login_Senha_PasswordField = new javax.swing.JPasswordField();
        Login_OK_botão = new javax.swing.JButton();
        primeiroCadastro_botão = new javax.swing.JButton();

        autenticar_jLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        autenticar_jLabel.setText("Autenticar Usuário");

        Login_SelecUsuario_label.setText("Selecionar Usuário:");

        senha_jLabel.setText("Senha:");

        Login_OK_botão.setText("OK");
        Login_OK_botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_OK_botãoActionPerformed(evt);
            }
        });

        primeiroCadastro_botão.setText("Primeiro Cadastro");
        primeiroCadastro_botão.setEnabled(false);
        primeiroCadastro_botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroCadastro_botãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(autenticar_jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(Login_OK_botão)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(primeiroCadastro_botão))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Login_SelecUsuario_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senha_jLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Login_SeletorUsuário_JComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Login_Senha_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(autenticar_jLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_SeletorUsuário_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_SelecUsuario_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha_jLabel)
                    .addComponent(Login_Senha_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_OK_botão)
                    .addComponent(primeiroCadastro_botão))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Login_OK_botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_OK_botãoActionPerformed
        
        Usuário user = ((Usuário) this.Login_SeletorUsuário_JComboBox.getSelectedItem()); //recupera o usuário da caixa de seleção de usuários
        
        if(user != null && user.PasswordMatch(new String(this.Login_Senha_PasswordField.getPassword())) ){
            //testa se a senha digitada bate com a do usuário selecionado
            UImaster.CurrentUser = user;
            UImaster.removeLoginScreen();
            JOptionPane.showMessageDialog(null, "Bem Vindo(a) "+ user.toString() + "!");
            UImaster.menuOPC();    
        }
        else{ 
            JOptionPane.showMessageDialog(null, "Senha Incorreta!"); //caso o método PasswordMatch falhe, o login não prossegue.
        }  
    }//GEN-LAST:event_Login_OK_botãoActionPerformed

    private void primeiroCadastro_botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroCadastro_botãoActionPerformed
        UImaster.PrimeiroCadastro(UImaster, true);
    }//GEN-LAST:event_primeiroCadastro_botãoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_OK_botão;
    private javax.swing.JLabel Login_SelecUsuario_label;
    private javax.swing.JComboBox<Usuário> Login_SeletorUsuário_JComboBox;
    private javax.swing.JPasswordField Login_Senha_PasswordField;
    private javax.swing.JLabel autenticar_jLabel;
    private javax.swing.JButton primeiroCadastro_botão;
    private javax.swing.JLabel senha_jLabel;
    // End of variables declaration//GEN-END:variables
}
