package Classes_UI;

import Classes_Base.Estoque;
import static Classes_Base.ListaDeVendas.adicionarPedido;
import static Classes_Base.ListaDeVendas.gravarLogVendas;
import Classes_Base.Pedido;
import Classes_Base.Produto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Está classe tem a função de gerenciar cada componente da interface gráfica da janela de vendas,atribuindo as funcionalidades aos componentes como labels,
 * textFields e botões.
 * @author niloc
 */
public class MenuVendas extends javax.swing.JFrame {
    //Um novo pedido é criado quando abre o menu de vendas
    private Pedido novoPedido = new Pedido();
    
    /**
     * Construtor de MenuVendas
     * @param vendedor usuário atual do programa
     */
    public MenuVendas(String vendedor) {
        initComponents();
        labelFunc.setText(vendedor);
        novoPedido.setIdVendedor(vendedor);
    }

    /**
     * Método que remove produto do carrinho de compras
     * @param nome nome do produto que será removido
     * @return true se o produto foi removido com sucesso, false se o produto não foi removido com sucesso(não está no carrinho)
     */
    public boolean removeProdCarrinho(String nome)
    {
        for(int i=0;i<novoPedido.getProdutosPedidos().size();i++)
        {
            if(novoPedido.getProdutosPedidos().get(i).getNome().equals(nome))
            {
                novoPedido.getProdutosPedidos().remove(i);
                return true;
            }
        }
        return false;
    }

    /**
     * Método que busca se algum produto já está no carrinho
     * @param nome nome do produto procurado
     * @return true se o produto está no carrinho de compras, false se não está
     */
    public boolean buscaProdCarrinho(String nome)
    {
        for(int i=0;i<novoPedido.getProdutosPedidos().size();i++)
        {
            if(novoPedido.getProdutosPedidos().get(i).getNome().equals(nome))
            {
                return true;
            }
        }
        return false;
    }

    /**
     * Método que altera a quantidade do produto pedido no carrinho
     * @param nome nome do produto
     * @param qtd nova quantidade adicionada
     */
    public void trocaQtdProdCarrinho(String nome,int qtd)
    {
        for(int i=0;i<novoPedido.getProdutosPedidos().size();i++)
        {
            if(novoPedido.getProdutosPedidos().get(i).getNome().equals(nome))
            {
                novoPedido.getProdutosPedidos().get(i).setQuantidade(qtd);
            }
        }
    }
    
    /**
     * Fecha o menu de venda
     */
    public void fecharJanela()
    {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFunc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textClienteName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxTP = new javax.swing.JComboBox<>();
        removButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        labelValorTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textQtd = new javax.swing.JTextField();
        textAddProd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textRemovProd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Abrir Venda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Funcionário:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome do cliente:");

        textClienteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClienteNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Forma de pagamento: ");

        comboBoxTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Crédito" }));
        comboBoxTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTPActionPerformed(evt);
            }
        });

        removButton.setText("Remover Produto");
        removButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Terminar Venda");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        addButton.setText("Adicionar Produto");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        labelValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelValorTotal.setText("valor");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total: R$");

        textQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtdActionPerformed(evt);
            }
        });

        textAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddProdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nome do Produto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantidade:");

        textRemovProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRemovProdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nome do Produto:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ADICIONAR PRODUTOS NO CARRINHO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("REMOVER PRODUTOS DO CARRINHO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textQtd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAddProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboBoxTP, 0, 134, Short.MAX_VALUE)
                                            .addComponent(textClienteName)
                                            .addComponent(labelFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textRemovProd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))))
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textClienteName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textRemovProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 47, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 46, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textClienteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClienteNameActionPerformed
        
    }//GEN-LAST:event_textClienteNameActionPerformed

    private void comboBoxTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTPActionPerformed

    private void removButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removButtonActionPerformed
        if(textRemovProd.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Erro, campo em branco.");
        }
        else
        {
            if(removeProdCarrinho(textRemovProd.getText()))
            {
                labelValorTotal.setText(""+novoPedido.somaTotalDosPedidos());
                JOptionPane.showMessageDialog(new JFrame(),"Produto Removido do carrinho.");
            }
            else
            {
               JOptionPane.showMessageDialog(new JFrame(),"Produto não consta no carrinho."); 
            }
        }
    }//GEN-LAST:event_removButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        if(((textClienteName.getText()).equals(""))||(novoPedido.getProdutosPedidos().isEmpty()))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Nome do cliente vazio ou carrinho vazio.");
        }
        else
        {
            novoPedido.setNomeCliente(textClienteName.getText());
            novoPedido.setTipoDePagamento(comboBoxTP.getSelectedItem()+"");
            JOptionPane.showMessageDialog(new JFrame(),"Venda Realizada. Valor: R$ "+novoPedido.somaTotalDosPedidos());
            adicionarPedido(novoPedido);
            for(int i=0;i<novoPedido.getProdutosPedidos().size();i++)
            {
                Estoque.reduzirQtdProduto(novoPedido.getProdutosPedidos().get(i).getNome(), novoPedido.getProdutosPedidos().get(i).getQuantidade());
            }
            gravarLogVendas();
            
            fecharJanela();
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(((textAddProd.getText()).equals(""))||((textQtd.getText()).equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Erro, campo em branco");
        }
        else
        {
          try {
            if(Estoque.buscarProduto(textAddProd.getText())!=null) //se a busca for diferente de null, o produto existe na lista
            {
                boolean flag=true;
                try {
                    int testaEntrada = Integer.parseInt(textQtd.getText()) - 1;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(new JFrame(),"Erro.");
                    flag=false;
                }
                if(flag==true)
                {
                    if((Integer.parseInt(textQtd.getText())>0)&&(Integer.parseInt(textQtd.getText())<= Estoque.buscarProduto(textAddProd.getText()).getQuantidade()))
                    {   //Se a qtd pedida for menor ou igual ao estoque, o pedido é valido e se a quantidade pedida for maior que zero também.
                        if(buscaProdCarrinho(textAddProd.getText()))
                        {
                            trocaQtdProdCarrinho(textAddProd.getText(),Integer.parseInt(textQtd.getText()));
                            labelValorTotal.setText(""+novoPedido.somaTotalDosPedidos());
                        }
                        else
                        {
                            novoPedido.getProdutosPedidos().add(new Produto(textAddProd.getText(),Integer.parseInt(textQtd.getText()),Estoque.buscarProduto(textAddProd.getText()).getPreco()));
                            labelValorTotal.setText(""+novoPedido.somaTotalDosPedidos());
                        }
                        JOptionPane.showMessageDialog(new JFrame(),"Produto adicionado ao carrinho.");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(new JFrame(),"Erro na quantidade pedida ou falta de estoque");        
                    }
                }
            } 
          }
            catch (NullPointerException e)
            {
                JOptionPane.showMessageDialog(new JFrame(),"Produto Inválido");
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void textQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtdActionPerformed

    private void textAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddProdActionPerformed

    private void textRemovProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRemovProdActionPerformed
        
    }//GEN-LAST:event_textRemovProdActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> comboBoxTP;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFunc;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JButton removButton;
    private javax.swing.JTextField textAddProd;
    private javax.swing.JTextField textClienteName;
    private javax.swing.JTextField textQtd;
    private javax.swing.JTextField textRemovProd;
    // End of variables declaration//GEN-END:variables
}
