package Classes_UI;

/**
 *
 * @author Mateus 9266410
 */
public class Menu_P extends javax.swing.JPanel {

   
    UIGovernor_F UImaster;
    
    
    
    protected void updateUserNameLabel(String newID){
        this.logadoComo_label.setText("Logado Como: " + newID);
    }
    
    public Menu_P(UIGovernor_F UImaster) {
        this.UImaster = UImaster;
        initComponents();
        this.logadoComo_label.setText("Logado Como: " + UImaster.CurrentUser.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirVenda_botão = new javax.swing.JButton();
        gerencProd_botão = new javax.swing.JButton();
        genrencUsuarios_botão = new javax.swing.JButton();
        emitRelatorios_botão = new javax.swing.JButton();
        uspLogo_label = new javax.swing.JLabel();
        logadoComo_label = new javax.swing.JLabel();

        abrirVenda_botão.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        abrirVenda_botão.setText("Abrir Venda");
        abrirVenda_botão.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abrirVenda_botão.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        abrirVenda_botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirVenda_botãoActionPerformed(evt);
            }
        });

        gerencProd_botão.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gerencProd_botão.setText("Gerenciamento de Produtos");
        gerencProd_botão.setToolTipText("");
        gerencProd_botão.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gerencProd_botão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerencProd_botãoMouseClicked(evt);
            }
        });

        genrencUsuarios_botão.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        genrencUsuarios_botão.setText("Gerenciamento de Usuários");
        genrencUsuarios_botão.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        genrencUsuarios_botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genrencUsuarios_botãoActionPerformed(evt);
            }
        });

        emitRelatorios_botão.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emitRelatorios_botão.setText("Emissão de Relatórios");
        emitRelatorios_botão.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emitRelatorios_botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitRelatorios_botãoActionPerformed(evt);
            }
        });

        uspLogo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usplogo.png"))); // NOI18N

        logadoComo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logadoComo_label.setText("Logado como: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(abrirVenda_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genrencUsuarios_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerencProd_botão)
                    .addComponent(emitRelatorios_botão)
                    .addComponent(uspLogo_label))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logadoComo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abrirVenda_botão, emitRelatorios_botão, genrencUsuarios_botão, gerencProd_botão});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(abrirVenda_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emitRelatorios_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerencProd_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genrencUsuarios_botão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(uspLogo_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(logadoComo_label)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirVenda_botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirVenda_botãoActionPerformed
        new AbrirVenda_F().makeFrameVendas(UImaster.CurrentUser.toString());
    }//GEN-LAST:event_abrirVenda_botãoActionPerformed

    private void gerencProd_botãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencProd_botãoMouseClicked
       UImaster.removeMenuOPC();
       UImaster.menuGerencProdutos();
    }//GEN-LAST:event_gerencProd_botãoMouseClicked

    private void genrencUsuarios_botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genrencUsuarios_botãoActionPerformed
        GrcUsuarios_F frame = new GrcUsuarios_F(UImaster);
        
    }//GEN-LAST:event_genrencUsuarios_botãoActionPerformed

    private void emitRelatorios_botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitRelatorios_botãoActionPerformed
        new AbrirRelatorio_F().makeFramePrincipal();
    }//GEN-LAST:event_emitRelatorios_botãoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirVenda_botão;
    private javax.swing.JButton emitRelatorios_botão;
    private javax.swing.JButton genrencUsuarios_botão;
    private javax.swing.JButton gerencProd_botão;
    private javax.swing.JLabel logadoComo_label;
    private javax.swing.JLabel uspLogo_label;
    // End of variables declaration//GEN-END:variables
}
